# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/tooldb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Flyway (optional but you already use it)
spring.flyway.enabled=true