// src/services/mockData.js
// 30 realistic seeded records for demo purposes
// DELETE this file and use real API when backend is ready

export const MOCK_RECORDS = [
  {
    id: 1,
    title: "Network Infrastructure Upgrade",
    description: "Complete overhaul of core network switches and routers across all floors.",
    category: "Infrastructure",
    status: "Active",
    priority: "High",
    score: 92,
    assignedTo: "Arjun Mehta",
    createdAt: "2026-04-01T09:00:00",
    updatedAt: "2026-04-20T14:30:00",
    dueDate: "2026-05-20",
    aiAnalysis: "High-priority infrastructure task with significant business impact. Recommend parallel deployment to minimize downtime.",
    tags: ["network", "hardware", "critical"],
  },
  {
    id: 2,
    title: "Security Patch Deployment",
    description: "Deploy CVE-2026-1234 security patches across all production servers.",
    category: "Security",
    status: "Completed",
    priority: "Critical",
    score: 98,
    assignedTo: "Priya Sharma",
    createdAt: "2026-04-03T10:15:00",
    updatedAt: "2026-04-10T16:00:00",
    dueDate: "2026-04-15",
    aiAnalysis: "Critical vulnerability addressed. All 47 servers patched successfully. No downtime reported.",
    tags: ["security", "patch", "production"],
  },
  {
    id: 3,
    title: "Database Performance Optimisation",
    description: "Analyse and fix slow queries in the reporting module causing 8s load times.",
    category: "Performance",
    status: "In Progress",
    priority: "High",
    score: 78,
    assignedTo: "Kiran Reddy",
    createdAt: "2026-04-05T11:00:00",
    updatedAt: "2026-04-22T09:45:00",
    dueDate: "2026-05-10",
    aiAnalysis: "3 queries identified with missing indexes. Estimated 70% improvement after optimisation.",
    tags: ["database", "performance", "backend"],
  },
  {
    id: 4,
    title: "User Onboarding Flow Redesign",
    description: "Redesign the 6-step onboarding to reduce drop-off rate from 42% to under 15%.",
    category: "UX",
    status: "Active",
    priority: "Medium",
    score: 85,
    assignedTo: "Sneha Patel",
    createdAt: "2026-04-06T08:30:00",
    updatedAt: "2026-04-21T13:00:00",
    dueDate: "2026-05-25",
    aiAnalysis: "UX audit reveals friction at step 3 (payment) and step 5 (verification). Recommend progressive disclosure.",
    tags: ["ux", "frontend", "conversion"],
  },
  {
    id: 5,
    title: "API Rate Limiting Implementation",
    description: "Add rate limiting to public APIs to prevent abuse and ensure fair usage.",
    category: "Security",
    status: "Completed",
    priority: "High",
    score: 90,
    assignedTo: "Rahul Nair",
    createdAt: "2026-04-07T09:00:00",
    updatedAt: "2026-04-18T17:00:00",
    dueDate: "2026-04-20",
    aiAnalysis: "Rate limiting successfully deployed. 429 responses handled gracefully. No false positives in first 48 hours.",
    tags: ["api", "security", "backend"],
  },
  {
    id: 6,
    title: "Cloud Cost Optimisation Review",
    description: "Audit AWS spend and identify resources to right-size or terminate.",
    category: "Infrastructure",
    status: "Active",
    priority: "Medium",
    score: 72,
    assignedTo: "Divya Kumar",
    createdAt: "2026-04-08T10:00:00",
    updatedAt: "2026-04-23T11:30:00",
    dueDate: "2026-05-15",
    aiAnalysis: "Estimated ₹2.4L/month savings identified across EC2, RDS, and unused S3 buckets.",
    tags: ["cloud", "aws", "cost"],
  },
  {
    id: 7,
    title: "CI/CD Pipeline Modernisation",
    description: "Migrate from Jenkins to GitHub Actions for faster build times.",
    category: "DevOps",
    status: "In Progress",
    priority: "Medium",
    score: 80,
    assignedTo: "Arjun Mehta",
    createdAt: "2026-04-09T09:30:00",
    updatedAt: "2026-04-24T15:00:00",
    dueDate: "2026-05-30",
    aiAnalysis: "Migration 60% complete. Build time reduced from 18min to 6min on migrated services.",
    tags: ["devops", "cicd", "automation"],
  },
  {
    id: 8,
    title: "GDPR Compliance Audit",
    description: "Full audit of data handling practices and documentation for GDPR compliance.",
    category: "Compliance",
    status: "Blocked",
    priority: "Critical",
    score: 55,
    assignedTo: "Priya Sharma",
    createdAt: "2026-04-10T08:00:00",
    updatedAt: "2026-04-25T10:00:00",
    dueDate: "2026-05-05",
    aiAnalysis: "Blocked pending legal team sign-off. 3 data processing activities require DPA agreements.",
    tags: ["compliance", "gdpr", "legal"],
  },
  {
    id: 9,
    title: "Mobile App Push Notifications",
    description: "Implement Firebase push notifications for iOS and Android apps.",
    category: "Feature",
    status: "Active",
    priority: "Low",
    score: 68,
    assignedTo: "Kiran Reddy",
    createdAt: "2026-04-11T11:00:00",
    updatedAt: "2026-04-22T16:30:00",
    dueDate: "2026-06-01",
    aiAnalysis: "Firebase integration straightforward. iOS requires APNs certificate renewal first.",
    tags: ["mobile", "firebase", "notifications"],
  },
  {
    id: 10,
    title: "Disaster Recovery Plan Update",
    description: "Update DR runbooks and test failover procedures for all critical systems.",
    category: "Infrastructure",
    status: "Active",
    priority: "High",
    score: 88,
    assignedTo: "Rahul Nair",
    createdAt: "2026-04-12T09:00:00",
    updatedAt: "2026-04-26T14:00:00",
    dueDate: "2026-05-18",
    aiAnalysis: "Last DR test was 14 months ago. Recommend full failover drill before May 18 deadline.",
    tags: ["dr", "infrastructure", "resilience"],
  },
  {
    id: 11,
    title: "Search Feature Elasticsearch Migration",
    description: "Migrate full-text search from PostgreSQL LIKE queries to Elasticsearch.",
    category: "Performance",
    status: "In Progress",
    priority: "High",
    score: 83,
    assignedTo: "Sneha Patel",
    createdAt: "2026-04-13T10:00:00",
    updatedAt: "2026-04-27T13:00:00",
    dueDate: "2026-05-28",
    aiAnalysis: "Index migration complete. Query latency dropped from 1200ms to 45ms in staging.",
    tags: ["search", "elasticsearch", "performance"],
  },
  {
    id: 12,
    title: "Employee Portal Single Sign-On",
    description: "Integrate Okta SSO across all internal tools and the employee portal.",
    category: "Security",
    status: "Completed",
    priority: "High",
    score: 95,
    assignedTo: "Divya Kumar",
    createdAt: "2026-04-01T08:00:00",
    updatedAt: "2026-04-16T17:00:00",
    dueDate: "2026-04-17",
    aiAnalysis: "SSO live across 12 tools. MFA adoption at 94%. 0 password reset tickets in first week.",
    tags: ["sso", "okta", "security"],
  },
  {
    id: 13,
    title: "Data Warehouse ETL Refactor",
    description: "Refactor nightly ETL jobs reducing runtime from 4 hours to under 45 minutes.",
    category: "Data",
    status: "In Progress",
    priority: "Medium",
    score: 76,
    assignedTo: "Arjun Mehta",
    createdAt: "2026-04-14T09:00:00",
    updatedAt: "2026-04-28T11:00:00",
    dueDate: "2026-06-05",
    aiAnalysis: "Bottleneck identified in customer_events table join. Partitioning strategy recommended.",
    tags: ["data", "etl", "warehouse"],
  },
  {
    id: 14,
    title: "Load Balancer Health Check Tuning",
    description: "Fix aggressive health check causing unnecessary instance restarts under load.",
    category: "Infrastructure",
    status: "Completed",
    priority: "Critical",
    score: 97,
    assignedTo: "Priya Sharma",
    createdAt: "2026-04-02T07:30:00",
    updatedAt: "2026-04-04T18:00:00",
    dueDate: "2026-04-05",
    aiAnalysis: "Root cause: 2s timeout too aggressive for Java cold starts. Increased to 10s. Zero restarts since fix.",
    tags: ["loadbalancer", "infrastructure", "stability"],
  },
  {
    id: 15,
    title: "Accessibility Compliance (WCAG 2.1)",
    description: "Audit and fix frontend accessibility issues to meet WCAG 2.1 AA standard.",
    category: "Compliance",
    status: "Active",
    priority: "Medium",
    score: 71,
    assignedTo: "Kiran Reddy",
    createdAt: "2026-04-15T10:00:00",
    updatedAt: "2026-04-29T14:00:00",
    dueDate: "2026-06-10",
    aiAnalysis: "42 accessibility violations found. High priority: missing alt text on 17 images, 8 forms without labels.",
    tags: ["accessibility", "wcag", "frontend"],
  },
  {
    id: 16,
    title: "Redis Cluster Setup",
    description: "Replace single Redis instance with Redis Cluster for high availability.",
    category: "Infrastructure",
    status: "Active",
    priority: "High",
    score: 86,
    assignedTo: "Rahul Nair",
    createdAt: "2026-04-16T09:00:00",
    updatedAt: "2026-04-30T12:00:00",
    dueDate: "2026-05-22",
    aiAnalysis: "3-node cluster configured in staging. Failover tested: 12ms recovery time. Ready for production.",
    tags: ["redis", "cache", "infrastructure"],
  },
  {
    id: 17,
    title: "API Documentation Portal",
    description: "Build a public developer portal with interactive API docs using Swagger.",
    category: "Feature",
    status: "Completed",
    priority: "Low",
    score: 79,
    assignedTo: "Sneha Patel",
    createdAt: "2026-04-03T11:00:00",
    updatedAt: "2026-04-22T15:30:00",
    dueDate: "2026-04-25",
    aiAnalysis: "Developer portal live at docs.sentineliq.io. 234 developers registered in first 3 days.",
    tags: ["api", "documentation", "developer"],
  },
  {
    id: 18,
    title: "Log Aggregation with ELK Stack",
    description: "Centralise logs from 15 microservices into Elasticsearch + Kibana.",
    category: "DevOps",
    status: "In Progress",
    priority: "Medium",
    score: 74,
    assignedTo: "Divya Kumar",
    createdAt: "2026-04-17T08:30:00",
    updatedAt: "2026-05-01T11:00:00",
    dueDate: "2026-05-30",
    aiAnalysis: "11 of 15 services shipping logs. 4 legacy services require Logstash pipeline configuration.",
    tags: ["elk", "logging", "devops"],
  },
  {
    id: 19,
    title: "Multi-Region Deployment",
    description: "Extend deployment to Mumbai and Singapore regions for lower latency.",
    category: "Infrastructure",
    status: "Active",
    priority: "High",
    score: 89,
    assignedTo: "Arjun Mehta",
    createdAt: "2026-04-18T09:00:00",
    updatedAt: "2026-05-02T14:30:00",
    dueDate: "2026-06-15",
    aiAnalysis: "Mumbai region reduces latency by 180ms for 60% of user base. Singapore adds resilience.",
    tags: ["cloud", "multiregion", "latency"],
  },
  {
    id: 20,
    title: "Payment Gateway Upgrade",
    description: "Migrate from Razorpay v1 to v2 API before July deprecation deadline.",
    category: "Feature",
    status: "Blocked",
    priority: "Critical",
    score: 60,
    assignedTo: "Priya Sharma",
    createdAt: "2026-04-19T10:00:00",
    updatedAt: "2026-05-03T09:00:00",
    dueDate: "2026-06-30",
    aiAnalysis: "Blocked on merchant ID verification with Razorpay support. Escalation raised on May 1.",
    tags: ["payment", "integration", "deadline"],
  },
  {
    id: 21,
    title: "Automated Regression Test Suite",
    description: "Build Playwright E2E test suite covering all critical user journeys.",
    category: "QA",
    status: "In Progress",
    priority: "Medium",
    score: 77,
    assignedTo: "Kiran Reddy",
    createdAt: "2026-04-20T09:30:00",
    updatedAt: "2026-05-04T13:00:00",
    dueDate: "2026-06-01",
    aiAnalysis: "48 test cases written. Coverage at 65%. Login, checkout, and dashboard flows fully covered.",
    tags: ["qa", "playwright", "automation"],
  },
  {
    id: 22,
    title: "Internal Knowledge Base Migration",
    description: "Migrate Confluence knowledge base to Notion with search improvements.",
    category: "Productivity",
    status: "Active",
    priority: "Low",
    score: 63,
    assignedTo: "Rahul Nair",
    createdAt: "2026-04-21T11:00:00",
    updatedAt: "2026-05-05T10:30:00",
    dueDate: "2026-06-20",
    aiAnalysis: "340 pages to migrate. Automated importer handles 80% successfully. 68 pages need manual review.",
    tags: ["productivity", "notion", "migration"],
  },
  {
    id: 23,
    title: "Monitoring & Alerting Overhaul",
    description: "Replace Nagios with Grafana + Prometheus for modern observability.",
    category: "DevOps",
    status: "Active",
    priority: "High",
    score: 84,
    assignedTo: "Sneha Patel",
    createdAt: "2026-04-22T08:00:00",
    updatedAt: "2026-05-06T14:00:00",
    dueDate: "2026-05-25",
    aiAnalysis: "Prometheus scraping 28 targets. 14 Grafana dashboards created. PagerDuty integration complete.",
    tags: ["monitoring", "grafana", "prometheus"],
  },
  {
    id: 24,
    title: "Microservices Service Mesh",
    description: "Deploy Istio service mesh for traffic management and mTLS between services.",
    category: "Infrastructure",
    status: "Active",
    priority: "Medium",
    score: 73,
    assignedTo: "Divya Kumar",
    createdAt: "2026-04-23T09:00:00",
    updatedAt: "2026-05-07T11:00:00",
    dueDate: "2026-06-25",
    aiAnalysis: "Istio control plane deployed. 6 of 15 services enrolled in mesh. mTLS active for enrolled services.",
    tags: ["istio", "servicemesh", "kubernetes"],
  },
  {
    id: 25,
    title: "Dark Mode Implementation",
    description: "Add full dark mode support across the web and mobile applications.",
    category: "UX",
    status: "Completed",
    priority: "Low",
    score: 82,
    assignedTo: "Arjun Mehta",
    createdAt: "2026-04-04T10:00:00",
    updatedAt: "2026-04-24T17:00:00",
    dueDate: "2026-04-28",
    aiAnalysis: "Dark mode shipped. 38% of users switched within 48 hours. App Store rating improved from 4.1 to 4.4.",
    tags: ["ux", "darkmode", "frontend"],
  },
  {
    id: 26,
    title: "Vendor SLA Tracking Dashboard",
    description: "Build real-time dashboard tracking SLA compliance across 12 vendors.",
    category: "Feature",
    status: "In Progress",
    priority: "Medium",
    score: 75,
    assignedTo: "Priya Sharma",
    createdAt: "2026-04-24T09:30:00",
    updatedAt: "2026-05-08T10:00:00",
    dueDate: "2026-06-05",
    aiAnalysis: "Data pipeline from vendor APIs established. Dashboard 70% complete. SLA breach alerts configured.",
    tags: ["dashboard", "vendor", "sla"],
  },
  {
    id: 27,
    title: "Container Security Hardening",
    description: "Apply CIS Docker Benchmark hardening to all production containers.",
    category: "Security",
    status: "Active",
    priority: "High",
    score: 87,
    assignedTo: "Kiran Reddy",
    createdAt: "2026-04-25T08:00:00",
    updatedAt: "2026-05-08T14:00:00",
    dueDate: "2026-05-20",
    aiAnalysis: "CIS score improved from 42% to 89%. Remaining items: non-root user enforcement on 3 legacy images.",
    tags: ["docker", "security", "cis"],
  },
  {
    id: 28,
    title: "API Versioning Strategy",
    description: "Implement v2 API with backward compatibility and deprecation policy.",
    category: "Feature",
    status: "Active",
    priority: "Medium",
    score: 70,
    assignedTo: "Rahul Nair",
    createdAt: "2026-04-26T10:00:00",
    updatedAt: "2026-05-09T09:30:00",
    dueDate: "2026-06-10",
    aiAnalysis: "v2 endpoints designed with URL versioning (/api/v2/). Sunset headers added to v1 responses.",
    tags: ["api", "versioning", "backend"],
  },
  {
    id: 29,
    title: "Real-Time Collaboration Features",
    description: "Add WebSocket-based real-time updates to shared documents and dashboards.",
    category: "Feature",
    status: "Active",
    priority: "Medium",
    score: 81,
    assignedTo: "Sneha Patel",
    createdAt: "2026-04-27T09:00:00",
    updatedAt: "2026-05-09T13:00:00",
    dueDate: "2026-06-20",
    aiAnalysis: "WebSocket server handles 1,200 concurrent connections in load test. Presence indicators working.",
    tags: ["websocket", "realtime", "collaboration"],
  },
  {
    id: 30,
    title: "Annual Penetration Testing",
    description: "Commission third-party pentest covering web app, APIs, and internal network.",
    category: "Security",
    status: "Active",
    priority: "Critical",
    score: 93,
    assignedTo: "Divya Kumar",
    createdAt: "2026-04-28T08:00:00",
    updatedAt: "2026-05-09T11:00:00",
    dueDate: "2026-05-31",
    aiAnalysis: "Pentest vendor onboarded. Scope document signed. Testing begins May 12. Report expected May 28.",
    tags: ["security", "pentest", "compliance"],
  },
];

// Derived stats for dashboard KPIs
export const MOCK_STATS = {
  total: 30,
  active: MOCK_RECORDS.filter(r => r.status === "Active").length,
  completed: MOCK_RECORDS.filter(r => r.status === "Completed").length,
  blocked: MOCK_RECORDS.filter(r => r.status === "Blocked").length,
  inProgress: MOCK_RECORDS.filter(r => r.status === "In Progress").length,
  avgScore: Math.round(MOCK_RECORDS.reduce((s, r) => s + r.score, 0) / MOCK_RECORDS.length),
  critical: MOCK_RECORDS.filter(r => r.priority === "Critical").length,
  byCategory: MOCK_RECORDS.reduce((acc, r) => {
    acc[r.category] = (acc[r.category] || 0) + 1;
    return acc;
  }, {}),
  byStatus: {
    Active: MOCK_RECORDS.filter(r => r.status === "Active").length,
    Completed: MOCK_RECORDS.filter(r => r.status === "Completed").length,
    "In Progress": MOCK_RECORDS.filter(r => r.status === "In Progress").length,
    Blocked: MOCK_RECORDS.filter(r => r.status === "Blocked").length,
  },
  monthlyTrend: [
    { month: "Nov", count: 3 },
    { month: "Dec", count: 5 },
    { month: "Jan", count: 7 },
    { month: "Feb", count: 9 },
    { month: "Mar", count: 14 },
    { month: "Apr", count: 30 },
  ],
};
